CREATE DATABASE MINIMARKET
USE MINIMARKET

DROP TABLE ADMINISTRADOR

CREATE TABLE ADMINISTRADOR(
CEDULA_ADMIN NUMERIC(10) PRIMARY KEY NOT NULL,
NOMBRE_ADMIN VARCHAR(25) NOT NULL,
CONTRASEÑA_ADMIN VARCHAR(20) NOT NULL
)

CREATE TABLE CAJERO(
CEDULA_CAJERO NUMERIC(10) PRIMARY KEY NOT NULL,
NOMBRE_CAJERO VARCHAR(15) NOT NULL,
APELLIDO_CAJERO VARCHAR(15) NOT NULL,
CONTRASEÑA_CAJERO VARCHAR(20) NOT NULL
)

CREATE TABLE VENTAS(
    COD_VENTA NUMERIC(5) PRIMARY KEY NOT NULL,
    CANTIDAD_VENTA NUMERIC(5) NOT NULL,
    IVA_VENTA FLOAT NOT NULL,
    SUB_TOTAL FLOAT NOT NULL,
    TOTAL FLOAT NOT NULL
)

CREATE TABLE PRODUCTOS(
  COD_PROD VARCHAR(10) PRIMARY KEY NOT NULL,
  NOM_PROD VARCHAR(20) NOT NULL,
  PRECIO FLOAT NOT NULL,
  STOCK NUMERIC NOT NULL
)

ALTER TABLE VENTAS 
ADD CEDULA_CAJEROFK NUMERIC(10) NOT NULL REFERENCES CAJERO (CEDULA_CAJERO)

ALTER TABLE VENTAS
ADD COD_PRODFK NUMERIC(10) NOT NULL REFERENCES PRODUCTOS (COD_PROD)


INSERT INTO ADMINISTRADOR VALUES(1718688284,"Wilson","patito1"),(1726025040,"Marlon","patito2"),(0504871195,"Melani","patito3"),(1723359327,"Josue","patito4")